# Generated by Django 4.2.4 on 2023-08-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.IntegerField(unique=True, verbose_name='articl')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('page', models.IntegerField(verbose_name='page')),
                ('state', models.CharField(choices=[('PUBLISH', 'PUBLISH'), ('MEAP', 'MEAP')], max_length=7, verbose_name='state')),
                ('author', models.ManyToManyField(related_name='book', to='author.author')),
                ('category', models.ManyToManyField(related_name='book', to='category.category')),
            ],
        ),
    ]
