# Generated by Django 4.2.4 on 2023-08-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('pk',)},
        ),
    ]
